Updated requirements.txt
Metannotate/Metannotate pull request #16
Opened 2017-08-16 19:43 UTC by RoranDangerous

2017-08-16 21:46 UTC, LeeBergstrand requested changes

2017-08-16 21:46 UTC, LeeBergstrand commented on requirements.txt
> +pyflakes==1.6.0
@RoranDangerous I don't think this package is required it may have already been on your system when you ```pip freeze```ed. please remove.

2017-08-16 22:24 UTC, RoranDangerous commented on requirements.txt
> +pyflakes==1.6.0
Which one is not required?

2017-08-16 22:24 UTC, LeeBergstrand commented on requirements.txt
> +pyflakes==1.6.0
PyFlakes

2017-08-16 22:50 UTC, RoranDangerous commented on requirements.txt
> +pyflakes==1.6.0
@LeeBergstrand I will check it and remove, if we don't need it

2017-08-16 22:53 UTC, RoranDangerous commented on requirements.txt
> +pyflakes==1.6.0
@LeeBergstrand  Updated

2017-08-16 22:55 UTC, LeeBergstrand requested changes

2017-08-16 22:55 UTC, LeeBergstrand commented on requirements.txt
>  taxtastic
@RoranDangerous taxtastic still needs a version number.

2017-08-16 23:21 UTC, RoranDangerous commented on requirements.txt
>  taxtastic
@LeeBergstrand I did not find taxatic through pip freeze

2017-08-16 23:36 UTC, LeeBergstrand commented on requirements.txt
>  taxtastic
https://pypi.python.org/pypi/taxtastic

2017-08-17 00:35 UTC, RoranDangerous commented on requirements.txt
>  taxtastic
@LeeBergstrand Done

2017-08-17 00:37 UTC, LeeBergstrand approved these changes
@RoranDangerous Thanks! :)

2017-08-17 00:37 UTC, merged