Improve taxonomy
Metannotate/Metannotate pull request #51
Opened 2017-12-10 06:41 UTC by LeeBergstrand

- Added pipefail to install dependancies. Fails if the install processes fails.
- Removed back up cache.
- Added call to taxonomy.py

- These changes have already been merged into develop.

2017-12-11 22:47 UTC, jmtsuji commented on .circleci/config.yml
>              - v1-pip-dependencies-{{ checksum "requirements.txt" }}
Now that only one key is present, consider moving from ```keys``` to ```key``` as mentioned [in the reference documentation for CircleCI](https://circleci.com/docs/2.0/configuration-reference/#restore_cache).

2017-12-11 22:48 UTC, jmtsuji requested changes
See comment in code about keys vs. key

2017-12-12 04:05 UTC, LeeBergstrand commented
@jmtsuji Fixed?

2017-12-12 15:35 UTC, jmtsuji approved these changes

2017-12-12 16:52 UTC, merged